#version: '3.8'
#
#services:
#  sonarqube:
#    image: sonarqube:developer
#    container_name: sonarqube
#    depends_on:
#      - postgres
#    ports:
#      - "9000:9000"
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/testing_db
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#    #      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
#    volumes:
#      - sonarqube_conf:/opt/sonarqube/conf
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_logs:/opt/sonarqube/logs
#      - sonarqube_extensions:/opt/sonarqube/extensions
#
#  postgres:
#    image: postgres:16
#    container_name: postgres
#    environment:
#      POSTGRES_DB: testing_db
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgresql:/var/lib/postgresql
#      - postgresql_data:/var/lib/postgresql/data
#
##  myapp:
###    image: myapp:latest
##    build: .
###      context: .
###      dockerfile: Dockerfile
##    container_name: myapp
##    ports:
##      - "8080:8080"
##    environment:
##      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testing_db
##      - SPRING_DATASOURCE_USERNAME=root
##      - SPRING_DATASOURCE_PASSWORD=root
##      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
##      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
##    depends_on:
##      - postgres
#
#volumes:
#  sonarqube_conf:
#  sonarqube_data:
#  sonarqube_logs:
#  sonarqube_extensions:
#  postgresql:
#  postgresql_data:



# FUNCIONA
version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/testing_db # jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: